spring:
  profiles:
    active: development
  application:
    name: "Come To Pi Ma"
  datasource:
    url: jdbc:postgresql://localhost:5432/cometopima?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    path: /swagger
    syntax-highlight:
      theme: monokai
      activated: true
    try-it-out-enabled: true
    tags-sorter: alpha
    filter: true

jwt:
  secret: F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq3t6w9z$C&F)J@McQfTjWnZr4u7x!A

# secondary port
server:
  port: 5000